services:
  - type: web
    name: agenda-contactos
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Agenda de Contactos"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: agenda-contactos
          type: web
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: agenda-contactos-db
          property: connectionString

databases:
  - name: agenda-contactos-db
    plan: free